name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1,3,5' # runs at 13:00 UTC every Mon., Wed., Fri.

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          lfs: true

      - name: Checkout LFS objects
        run: git lfs pull

      - name: fetch latest files from password protected NDS Open Area
        env: 
          OPENAREA_USER: ${{ secrets.OPENAREA_USER }}
          OPENAREA_PWD: ${{ secrets.OPENAREA_PWD }}
        run: |
            wget -nv -N --no-if-modified-since --no-use-server-timestamps --user $OPENAREA_USER --password $OPENAREA_PWD \
            --user-agent="OECD" --no-directories --content-disposition --restrict-file-names=nocontrol -e robots=off \
            -A "trans.*" --directory-prefix=trans_files --check-certificate=quiet -r -l 0  --no-parent www-nds.iaea.org/nrdc/ndsx4/trans/


      - name: commit new files and changes
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git lfs track "trans.*"
            git add trans*
            git commit -m "auto update trans files"
            git push origin main
